baseURL = 'https://kiranjthomas.com/'
languageCode = 'en-us'
title = 'Kiran Thomas'
theme = 'anatole'

[params]
    title = "I'm Kiran Thomas"
    author = "Kiran Thomas"
    profilePicture = "images/profile.jpeg"
    displayMode = "dark"
    description = """
    I'm a Software Engineer in Austin, TX.
    I am an AWS Certified Solutions Architect.
    """

    [[params.socialIcons]]
    icon = "fab fa-linkedin"
    title = "Linkedin"
    url = "https://www.linkedin.com/in/kiranjthomas/"

    [[params.socialIcons]]
    icon = "fab fa-github"
    title = "Github"
    url = "https://github.com/kiranjthomas"

    [[params.socialIcons]]
    icon = "fas fa-envelope"
    title = "e-mail"
    url = "mailto:kiranjthomas@gmail.com"

[menu]
    [[menu.main]]
    name = "Posts"
    weight = 200
    identifier = "posts"
    url = "/posts/"

    [[menu.main]]
    name = "About"
    weight = 300
    identifier = "about"
    url = "/about/"
