[[main]]
name = "Home"
identifier = "home"
weight = 100
url = "/"

[[main]]
name = "Posts"
weight = 300
identifier = "posts"
url = "/posts/"

[[main]]
name = "Projects"
weight = 300
identifier = "projects"
url = "/projects/"

[[main]]
name = "About"
weight = 300
identifier = "about"
url = "/about/"
