name: scp build folder

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./ui

    steps:
      - uses: actions/checkout@v2
        name: Pull from GitHub
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - run: npm ci
      - run: npm run build --if-present
        env:
          CI: false
      - run: ls build
      - run: pwd build
      - uses: appleboy/scp-action@master
        name: scp files
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          source: "ui/build/*"
          target: "/home/kiran/kiranjthomas/edge/build/www/personal"
          strip_components: 2
