name: Build and Deploy Static Assets

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Pull from GitHub
        uses: actions/checkout@v3
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod
      - name: Run markdown linter
        uses: DavidAnson/markdownlint-cli2-action@v9
        with:
          command: config
          globs: |
            .markdownlint.json
            content/*.md
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true
      - name: Build Hugo
        run: hugo --minify
      - name: SCP static files
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          source: "public/*"
          target: "/home/kiran/kiranjthomas/edge/build/www/personal"
          strip_components: 1
